### PR TITLE
RESTEASY-2206 cleanup resteasy-example project

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
@asoldano Could you please help to check if this modification is in right direction? If so I'll go on working on it to enable all the workbook examples.

**Comment by liweinan** [comment]
@asoldano okay I'll investigate on it and give my findings here.

**Comment by liweinan** [comment]
@asoldano I have found the problem and created a sample project here:

> https://github.com/liweinan/resteasy-dependencies-sample

If I use `resteasy-dependencies` as `bom`:

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jboss.resteasy</groupId>
                <artifactId>resteasy-dependencies</artifactId>
                <version>${resteasy.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
``` 

Then project will work correctly:

```bash
$ mvn jetty:run
```

image

If I used `resteasy-dependencies` as project parent:

```xml
<parent>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-dependencies</artifactId>
    <version>4.3.0.Final</version>
</parent>
```

Then running embedded jetty server will throw exception:

image

So in general the `resteasy-dependencies` should be used as `bom` instead of `parent`. Do you agree with this conclusion? If so I'll modify this PR to use `resteasy-dependencies` as `bom`.

**Comment by asoldano** [comment]
@liweinan I agree, yes

**Comment by liweinan** [comment]
@asoldano thanks! okay I know what to do next.

- I'll add resteasy-dependency as a bom and remove unnecessary versions in the examples.
- I'll merge this PR after I've done the changes and go on working on the rest of the examples to re-enable them properly.

**Pull request merged**
