### PR TITLE
Add JSON format header fetching method in tracing example README.

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by jamezp** [comment]
This isn't quite what I was thinking. I'll work on a PR to show what I mean.

**Comment by jamezp** [comment]
@liweinan I was thinking more something like this. If you run this and go to http://localhost:8080/tracing-example/headers/client/get you'll see what I mean.

I'm making it a draft now because I might make an index that displays the headers from a JavaScript call. However, that might break the previous versions of this example.

**Comment by liweinan** [comment]
> @liweinan I was thinking more something like this. If you run this and go to http://localhost:8080/tracing-example/headers/client/get you'll see what I mean.
> 
> I'm making it a draft now because I might make an index that displays the headers from a JavaScript call. However, that might break the previous versions of this example.

Cool!

for reference: https://github.com/resteasy/resteasy-examples/pull/124

**Comment by jamezp** [comment]
I'm only closing this because there is a conflict and I think the example is too busy for the README. If you do not agree please feel free to reopen it.

**Pull request closed without merging**
