### PR TITLE
add the missing layers and feature-pack location config for the boota…

### PR DESCRIPTION
**Pull request by liweinan**
…ble-jar example. #109

### CODE REVIEW

**Comment by liweinan** [comment]
without the config section the example won't run.

**Comment by liweinan** [comment]
Adding the config section will cause the problem in Github CI, otherwise comment out the config section will generate the following error:

image

when running:

```bash
➤ mvn wildfly-jar:package                                                                                                                                           00:30:17
```

**Comment by liweinan** [comment]
@jamezp I have no idea how to fix this problem properly, could you please have a look at this? Thanks!

**Comment by jamezp** [comment]
You can't define a `<feature-pack-location/>` and `<feature-pack/>`. However, the example seems to work fine for me. How are you trying to build it?

**Comment by liweinan** [comment]
> You can't define a `<feature-pack-location/>` and `<feature-pack/>`. However, the example seems to work fine for me. How are you trying to build it?

Firstly, I build the whole project without the config in this branch:

```bash
$ mvn clean install -DskipTests
```

Then I entered the `bootable-jar` directory and run the wildfly plugin package command:

```bash
➤ mvn wildfly:package
```

And it will throw the following error:

```
[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:8.1.0.Final:package (default-cli) on project products-runner: Provisioning failed: No valid provisioning configuration, you must set a feature-pack-location, a list of feature-packs or use a provisioning.xml file -> [Help 1]
```

image

Then I added the config in this PR branch and rerun the command, and the example works:

image

**Comment by jamezp** [comment]
Ah, okay I see. The problem is the configuration is defined in the execution. Running `mvn clean package` will execute the `wildfly-jar:package` goal. I created a PR, #111, which just moves the configuration. That should be all that needs to be done.

The reason you see the failure on `mvn package` is because it enables the executions configuration as well as the global configuration on the plugin.

**Comment by liweinan** [comment]
@jamezp Thanks for help!

**Pull request closed without merging**
