### PR TITLE
RESTEASY-2491 remove log4j dependency  and add dependency enforcer rules

### PR DESCRIPTION
**Pull request by liweinan**
****

### CODE REVIEW

**Comment by liweinan** [comment]
Currently the `doseta-use-dns-example` relies on `resteasy-eagledns-fork`:

image

And the current release of `resteasy-eagledns-fork` relies on `log4j` and it will fail after removing the `log4j` dependency:

image

It seems this PR is related:

https://github.com/resteasy/resteasy-extensions/pull/8

@asoldano  I guess we should have a new release of `resteasy-extensions`, wdyt? I can do the release if necessary.

**Comment by asoldano** [comment]
> Currently the `doseta-use-dns-example` relies on `resteasy-eagledns-fork`:
> 
> image
> 
> And the current release of `resteasy-eagledns-fork` relies on `log4j` and it will fail after removing the `log4j` dependency:
> 
> image
> 
> It seems this PR is related:
> 
> [resteasy/resteasy-extensions#8](https://github.com/resteasy/resteasy-extensions/pull/8)
> 
> @asoldano I guess we should have a new release of `resteasy-extensions`, wdyt? I can do the release if necessary.

Hi @liweinan ,
have you tried moving to version 1.0.0.Final (that I tagged after https://github.com/resteasy/resteasy-extensions/pull/8 ) ? Does that help?

**Comment by liweinan** [comment]
@asoldano okay! let me try :-)

**Comment by liweinan** [comment]
@asoldano After I upgraded the `resteasy-extensions` to newest release I cat get rid of `log4j` dependency. Thanks for help!

btw this PR is ready for merging, could you please help to review it? Thanks!

**Pull request merged**
